/* Course assistant for PHYS 106 Astronomy: chat button
   Generated by the faculty walkthrough. Add this file to your site, then paste
   the one-line script tag from Step 7 just above the closing body tag of each page.
   You can change the settings in CONFIG below by hand at any time. */
(function () {
  "use strict";
  var CONFIG = {
    workerUrl: "https://phys106-assistant.mqaissaunee.workers.dev/",
    title: "PHYS 106 Astronomy assistant",
    greeting: "Hi! I'm the course assistant for PHYS 106 Astronomy. Ask me to explain anything on this page: a concept, a term, or a step you're stuck on.\n\nI won't do graded work for you, but I'm happy to help you understand how to do it.",
    note: "AI can be wrong. Check important answers, and don't share personal information.",
    color: "#14324a",
    pageSelector: "main",
    maxPageChars: 15000
  };
  if (!CONFIG.workerUrl || document.getElementById("ca-launch")) return;

  var KEY = "course-assistant:" + location.pathname;
  var history = [], busy = false, open = false, pageText = null;
  var launch, panel, log, input, send;

  var css = [
    ".ca-launch{position:fixed;right:18px;bottom:18px;z-index:2147483000;display:flex;align-items:center;gap:8px;min-height:48px;padding:0 18px;border:0;border-radius:999px;background:" + CONFIG.color + ";color:#fff;font:600 15px/1 system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;box-shadow:0 4px 14px rgba(0,0,0,.25);cursor:pointer}",
    ".ca-launch:focus-visible,.ca-panel button:focus-visible,.ca-panel textarea:focus-visible,.ca-log:focus-visible{outline:3px solid #1f6fd1;outline-offset:2px}",
    ".ca-panel{position:fixed;right:18px;bottom:78px;z-index:2147483000;width:min(400px,calc(100vw - 24px));height:min(560px,calc(100vh - 110px));display:flex;flex-direction:column;background:#fff;color:#1d2a33;border:1px solid #c3d1da;border-radius:12px;box-shadow:0 10px 30px rgba(0,0,0,.25);font:15px/1.5 system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;overflow:hidden}",
    ".ca-panel[hidden]{display:none}",
    ".ca-head{display:flex;align-items:center;gap:6px;padding:8px 8px 8px 14px;background:" + CONFIG.color + ";color:#fff}",
    ".ca-head b{flex:1;font-size:15px}",
    ".ca-icon{min-width:40px;min-height:40px;border:0;border-radius:8px;background:transparent;color:#fff;font-size:18px;cursor:pointer}",
    ".ca-icon:hover{background:rgba(255,255,255,.18)}",
    ".ca-log{flex:1;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:10px;background:#f4f7f9}",
    ".ca-msg{max-width:88%;padding:9px 12px;border-radius:12px;overflow-wrap:anywhere}",
    ".ca-user{align-self:flex-end;background:" + CONFIG.color + ";color:#fff;white-space:pre-wrap}",
    ".ca-bot{align-self:flex-start;background:#fff;border:1px solid #d7e1e8}",
    ".ca-bot p{margin:0 0 8px}.ca-bot p:last-child{margin:0}",
    ".ca-bot ul,.ca-bot ol{margin:0 0 8px;padding-left:20px}",
    ".ca-bot code{background:#eef3f6;padding:1px 4px;border-radius:4px;font:13px ui-monospace,Menlo,Consolas,monospace}",
    ".ca-bot pre{background:#13283a;color:#e6eef4;padding:10px;border-radius:8px;overflow-x:auto;margin:0 0 8px}",
    ".ca-bot pre code{background:none;color:inherit;padding:0}",
    ".ca-dots span{display:inline-block;width:7px;height:7px;margin:0 2px;border-radius:50%;background:#7a8c99;animation:ca-b 1s infinite ease-in-out}",
    ".ca-dots span:nth-child(2){animation-delay:.15s}.ca-dots span:nth-child(3){animation-delay:.3s}",
    "@keyframes ca-b{0%,80%,100%{opacity:.3}40%{opacity:1}}",
    "@media (prefers-reduced-motion:reduce){.ca-dots span{animation:none}}",
    ".ca-foot{display:flex;gap:8px;padding:10px;border-top:1px solid #d7e1e8;background:#fff}",
    ".ca-foot textarea{flex:1;resize:none;min-height:44px;max-height:120px;padding:10px;border:1.5px solid #c3d1da;border-radius:8px;font:inherit;color:inherit}",
    ".ca-send{min-width:64px;min-height:44px;border:0;border-radius:8px;background:" + CONFIG.color + ";color:#fff;font:600 14px system-ui,sans-serif;cursor:pointer}",
    ".ca-send:disabled{opacity:.5;cursor:not-allowed}",
    ".ca-note{margin:0;padding:6px 12px 10px;font-size:12px;color:#4f5f6b;background:#fff}",
    ".ca-vh{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}",
    "@media (prefers-color-scheme:dark){.ca-panel{background:#16252f;color:#dde6ec;border-color:#2f4655}.ca-log{background:#0f1a22}.ca-bot{background:#16252f;border-color:#2f4655}.ca-bot code{background:#1d2f3b}.ca-foot,.ca-note{background:#16252f;border-color:#2f4655}.ca-note{color:#a5b5c0}.ca-foot textarea{background:#0f1a22;border-color:#2f4655}}"
  ].join("\n");

  function el(tag, attrs, text) {
    var n = document.createElement(tag);
    if (attrs) for (var k in attrs) { if (k === "class") n.className = attrs[k]; else n.setAttribute(k, attrs[k]); }
    if (text != null) n.textContent = text;
    return n;
  }
  function esc(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }

  // Light Markdown: code blocks, inline code, bold, lists, paragraphs. All text is escaped first.
  function md(src) {
    var blocks = [];
    var s = String(src).replace(/```[\w+-]*\n?([\s\S]*?)```/g, function (m, code) { blocks.push(code.replace(/\s+$/, "")); return "\u0000" + (blocks.length - 1) + "\u0000"; });
    s = esc(s)
      .replace(/`([^`\n]+)`/g, "<code>$1</code>")
      .replace(/\*\*([^*\n]+)\*\*/g, "<strong>$1</strong>");
    s = s.split(/\n{2,}/).map(function (para) {
      var lines = para.trim().split("\n");
      if (!lines[0]) return "";
      if (lines.every(function (l) { return /^\s*[-*] /.test(l); })) return "<ul>" + lines.map(function (l) { return "<li>" + l.replace(/^\s*[-*] /, "") + "</li>"; }).join("") + "</ul>";
      if (lines.every(function (l) { return /^\s*\d+\. /.test(l); })) return "<ol>" + lines.map(function (l) { return "<li>" + l.replace(/^\s*\d+\. /, "") + "</li>"; }).join("") + "</ol>";
      if (/^\u0000\d+\u0000$/.test(para.trim())) return para.trim();
      return "<p>" + lines.join("<br>") + "</p>";
    }).join("");
    return s.replace(/\u0000(\d+)\u0000/g, function (m, i) { return "<pre><code>" + esc(blocks[+i]) + "</code></pre>"; });
  }

  // The text of the page the student is reading, sent with each question.
  function readPage() {
    if (pageText !== null) return pageText;
    var root = document.querySelector(CONFIG.pageSelector) || document.body;
    var copy = root.cloneNode(true);
    copy.querySelectorAll("script,style,noscript,nav,button,.ca-panel,.ca-launch").forEach(function (n) { n.remove(); });
    var heading = document.querySelector("h1");
    var text = (document.title + (heading ? "\n" + heading.textContent : "") + "\n\n" + (copy.innerText || copy.textContent || ""))
      .replace(/\n{3,}/g, "\n\n").trim();
    pageText = text.slice(0, CONFIG.maxPageChars);
    return pageText;
  }

  function save() { try { sessionStorage.setItem(KEY, JSON.stringify(history.slice(-24))); } catch (e) {} }
  function load() { try { var h = JSON.parse(sessionStorage.getItem(KEY)); if (Array.isArray(h)) history = h; } catch (e) {} }

  function add(role, content, typing) {
    var wrap = el("div", { class: "ca-msg " + (role === "user" ? "ca-user" : "ca-bot") });
    wrap.appendChild(el("span", { class: "ca-vh" }, role === "user" ? "You said: " : "Assistant said: "));
    var body = el("div");
    if (typing) { body.className = "ca-dots"; body.setAttribute("aria-label", "Assistant is typing"); body.innerHTML = "<span></span><span></span><span></span>"; }
    else if (role === "user") body.textContent = content;
    else body.innerHTML = md(content);
    wrap.appendChild(body);
    log.appendChild(wrap);
    log.scrollTop = log.scrollHeight;
    return wrap;
  }
  function paint() {
    log.textContent = "";
    add("assistant", CONFIG.greeting);
    history.forEach(function (m) { add(m.role, m.content); });
  }
  function setBusy(b) { busy = b; send.disabled = b; input.disabled = b; }
  function grow() { input.style.height = "auto"; input.style.height = Math.min(120, input.scrollHeight) + "px"; }

  function ask() {
    var q = input.value.trim();
    if (!q || busy) return;
    input.value = ""; grow();
    history.push({ role: "user", content: q }); save();
    add("user", q);
    var dots = add("assistant", "", true);
    setBusy(true);
    fetch(CONFIG.workerUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ messages: history.slice(-12), context: readPage() })
    }).then(function (r) {
      if (r.status === 429) throw new Error("rate");
      if (r.status === 502) throw new Error("upstream");
      if (!r.ok) throw new Error("http");
      return r.json();
    }).then(function (data) {
      dots.remove();
      var a = (data && data.reply) || "Sorry, I didn't get an answer. Please try rephrasing.";
      history.push({ role: "assistant", content: a }); save();
      add("assistant", a);
    }).catch(function (e) {
      dots.remove();
      add("assistant", e.message === "rate"
        ? "The assistant is busy right now. Please try again in a minute."
        : e.message === "upstream"
        ? "The AI service didn't answer this time. It may be busy. Please try again in a moment."
        : "Sorry, I couldn't reach the assistant. Check your connection and try again.");
    }).then(function () { setBusy(false); input.focus(); });
  }

  function toggle(state) {
    open = state == null ? !open : state;
    panel.hidden = !open;
    launch.setAttribute("aria-expanded", String(open));
    if (open) { if (!log.childNodes.length) paint(); setTimeout(function () { input.focus(); }, 30); }
    else launch.focus();
  }

  function build() {
    var style = el("style"); style.textContent = css; document.head.appendChild(style);
    launch = el("button", { type: "button", id: "ca-launch", class: "ca-launch", "aria-expanded": "false", "aria-controls": "ca-panel" });
    launch.appendChild(el("span", { "aria-hidden": "true" }, "\uD83D\uDCAC"));
    launch.appendChild(el("span", null, "Ask the assistant"));
    panel = el("div", { id: "ca-panel", class: "ca-panel", role: "dialog", "aria-label": CONFIG.title, hidden: "" });
    var head = el("div", { class: "ca-head" });
    head.appendChild(el("b", null, CONFIG.title));
    var fresh = el("button", { type: "button", class: "ca-icon", "aria-label": "Start a new conversation", title: "New conversation" }, "\u21BB");
    var close = el("button", { type: "button", class: "ca-icon", "aria-label": "Close the assistant", title: "Close" }, "\u2715");
    head.appendChild(fresh); head.appendChild(close);
    log = el("div", { class: "ca-log", role: "log", "aria-live": "polite", "aria-label": "Conversation", tabindex: "0" });
    var foot = el("form", { class: "ca-foot" });
    input = el("textarea", { rows: "1", "aria-label": "Ask a question", placeholder: "Ask about this page\u2026" });
    send = el("button", { type: "submit", class: "ca-send" }, "Send");
    foot.appendChild(input); foot.appendChild(send);
    panel.appendChild(head); panel.appendChild(log); panel.appendChild(foot);
    panel.appendChild(el("p", { class: "ca-note" }, CONFIG.note));
    document.body.appendChild(launch); document.body.appendChild(panel);

    launch.addEventListener("click", function () { toggle(); });
    close.addEventListener("click", function () { toggle(false); });
    fresh.addEventListener("click", function () { history = []; save(); paint(); input.focus(); });
    foot.addEventListener("submit", function (e) { e.preventDefault(); ask(); });
    input.addEventListener("input", grow);
    input.addEventListener("keydown", function (e) { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); ask(); } });
    document.addEventListener("keydown", function (e) { if (e.key === "Escape" && open) { e.preventDefault(); toggle(false); } });
  }

  load();
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", build); else build();
})();
